### ISSUE TITLE
Milestones that have been closed or renamed are still showing in the Milestone filter dropdown

### ISSUE THREAD

**Issue by olshiftyeye** [ZenHubIO/support#306]
![](http://ss.imjp.me/20150710110041.png)

While looking at one repository that only has one open milestone (`Milestone 3 (Front End)`), I'm still seeing `Milestone 2` which has been closed for days, and `Milestone 3` which has since been renamed to `Milestone 3 (Front End)`.

Here's the default GitHub UI of my milestones for reference:

Open milestones:
![](http://ss.imjp.me/20150710110457.png)

Closed milestones:
![](http://ss.imjp.me/20150710110532.png)

---

You may be wondering why I suddenly renamed `Milestone 3` to `Milestone 3 (Front End)`. I currently have two repos that pertain to work I'm doing for one customer, and I had a `Milestone 3` in each repository. As you can imagine it got a little confusing when I had both repos connected to my ZenHub board and then tried to filter by milestone -- which `Milestone 3` is which?
![](http://ss.imjp.me/20150710111010.png)

 I thought renaming them to `Milestone 3 (Front End)` and `Milestone 3 (Back end)` would help, but now it's caused this weird bug to occur (as detailed above).

So I guess that's three issues to deal with:
- [ ] Why are closed/renamed milestones showing up in my milestone filter?
- [ ] Why are issues assigned to `Milestone 3 (Front End)` not showing up when I filter by that milestone?
- [ ] Can you include some designation of which repo a milestone belongs to in the milestone filter dropdown?

**Comment by ppuleo** [comment]
I'm seeing the same issue without renaming milestones. For approximately the past month, closed milestones remain in the milestone filter. For example:

#### Closed Milestone
![milestone-closed](https://cloud.githubusercontent.com/assets/1873201/8808649/be36e44a-2f98-11e5-9f0b-cf6b3966d9e6.png)

#### Milestone Filter
![milestone-filter](https://cloud.githubusercontent.com/assets/1873201/8808653/c3223cac-2f98-11e5-9b72-b5233800273c.png)

**Comment by olshiftyeye** [comment]
@ppuleo i've noticed that happens when there are still issues in the milestone (even if those issues are closed). as a hacky fix, i've just created a `Closed Issues` milestone where I dump all closed issues at the same time I close out a milestone. that should take care of it appearing in the dropdown. hopefully we'll get a more elegant fix at some point though.

**Comment by ppuleo** [comment]
@olshiftyeye Interesting note, thanks. I'd like to keep the issue/milestone relationship history intact so I probably won't go back through all the issues and remove the milestone to hide it from the filter. But that observation should be useful in troubleshooting the problem.

**Comment by aupright** [comment]
Hey @olshiftyeye and @ppuleo thanks for reaching out—I apologize for my late reply here!

The issues that you are noticing with respect to closed milestones and milestone re-names are both due to inconsistencies that we are experiencing with the milestone cache (see https://github.com/ZenHubIO/support/issues/244). As mentioned in that issue, these inconsistencies are due to the fact that GitHub does not treat milestone re-names as an update when we send them an API call to ask for any updates to the issue list. We've since implemented a preliminary fix, and are currently moving towards a permanent fix to better handle these cases.

>Can you include some designation of which repo a milestone belongs to in the milestone filter dropdown? 

I think this is a great suggestion that would add another layer of organization for teams that are working across repos with many milestones. While I can't make any promises as to whether we can implement this, I'll definitely bring this up with the rest of the team to as something to explore further going forward.

Finally, in order to keep the discussion centralized, I'm going to close out this issue and move the conversation over to #244. We'll be updating our progress towards a long term fix in that thread, so keep a look out for future updates there!

**Comment by seanseany** [comment]
I have DELETED a milestone, but the Milestone is still inside the Zenhub. Here is the screenshot:
<img width="1270" alt="screen shot 2017-05-09 at 12 53 10 pm" src="https://cloud.githubusercontent.com/assets/7416639/25862587/8f4cdb24-34b6-11e7-816c-ae97f78d5db4.png">

**Comment by kendramoroz** [comment]
@seanseany thanks for reporting this! Deleted milestones should be removed from the dropdown as all associated issues will become unassigned once deleted. I see that the MVP dropdown has the `due in 4 months` tag. Can you confirm in the milestones list from the GitHub UI that it was in fact deleted and didn't error out? In addition, can you send over the organization/repo name where you're seeing this happen and we can continue to debug on our end? Feel free to send us a screenshot/additional details to support@zenhub.com if you'd prefer to not have them listed publicly!

**Comment by seanseany** [comment]
The issue was there was an issue hiding in the Closed pipeline on the right, which I didn't see! Problem is resolved 👍

**Comment by kendramoroz** [comment]
@seanseany great to hear! Let me know if anything else comes up I can help with :)
