### ISSUE TITLE
Implement time estimation tracking for Issues

### ISSUE THREAD

**Issue by Jessalyst** [ZenHubIO/support#69]
Time tracking would allow you to monitor the time status of projects as well as the ability to forecast for future projects.

We'd love to know if this would be useful to your workflows and if so, how you would use the feature!

**Comment by joeltello** [comment]
+1 for this and burndown charts

**Comment by bcherny** [comment]
another +1 for this and burndowns

**Comment by posabsolute** [comment]
another +1 for this and burndowns

**Comment by hussfelt** [comment]
This is interesting, but has been left open for a year... :)
Is this something you guys at ZenHub see coming?

**Comment by azenMatt** [comment]
@hussfelt - Yes! and soon

Stand ready for a plethora of new ZenHub features over the next couple of months :smile:

**Comment by hussfelt** [comment]
@azenMatt soon as in "look at our public release-schedule here: ***"? ;-)

**Comment by azenMatt** [comment]
![burndowncharts02](https://cloud.githubusercontent.com/assets/7263690/7603361/3c7bc680-f908-11e4-9822-3b61d8b60835.gif)

Time estimation tracking in GitHub is here! 

If you update to version 2.1.8 you will now be able to create and add estimates to an issue - and view a milestone based burndown chart from these estimates. 

We have lots of exciting additions we would like to add to this feature in the coming weeks - but wanted to get this milestone approach live for everyone to start using as soon as it was ready! :shipit:  

A couple of improvements that will be released in the near future: 

- [ ] Displaying estimates in the ZenHub Board view 

- [ ] The ability to see burndown charts for closed milestones 

- [ ] Estimates on closed issue pages 

I can think of lots of other ways teams will want to use ZenHub burndown charts inside GitHub, it would be great to get some feedback either in this issue - or to discuss in a google hangout. If you would like to help shape this feature please drop me an email - support@zenhub.io - and we can organize a time to chat about it!

**Comment by Mottie** [comment]
@azenMatt If a milestone as associated text (Markdown), it is not rendered within the "gh-header-meta" div. I just see plain text ([example](https://github.com/Mottie/tablesorter#burndown)).

**Comment by azenMatt** [comment]
Thanks for the feedback @Mottie 

For the first issue - we will add that to our v1.1 of this feature! 

For the second issue - this is permission based - you will only be able to change this where you have push access (which is the same as pipelines are currently)

**Comment by azenMatt** [comment]
Closing this issue now that we have estimates live in the ZenHub board!

![image](https://cloud.githubusercontent.com/assets/7584089/9076015/a0f80f14-3ad1-11e5-9d7d-2ff92ad97bdc.png)

**Comment by BrunoBernardino** [comment]
Awesome!

**Comment by nicoleervin** [comment]
I still don't see this as an option on issues. Where do I go to find it?

**Comment by azenMatt** [comment]
Hi @nicoleervin - what do you not see here? The ability to add an estimate or to see and estimate on the board? 

Can you send an email to Support@ZenHub.io and we can look into this for you? Thanks

**Comment by pablopaul** [comment]
@azenMatt Is it possible to track changing estimates in a form of a extended burn down chart? https://www.mountaingoatsoftware.com/blog/improving-on-traditional-release-burndown-charts

**Comment by azenMatt** [comment]
Hi @pablopaul - that looks interesting. I have captured it into an issue here #799 so it doesn't get lost at the bottom of this one.

**Comment by ramitfwrk** [comment]
Hi I need to add Custom Time Estimation hours to issue . please help..
